import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Banner from '../components/banner/banner.component';
import BannerImg from '../components/banner-image/banner-img.component';
import Certificate from '../components/certificate/certificate.component';
import Mission from '../components/mission/mission.component';
import HomeServices from '../components/home-services/home-services.component';
import Link from 'next/link';
import DarkAngle from '../public/static/dark-angle.svg'
const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        
        <title>Psi | Home</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <div className={styles.homeWrapper}>
      <Banner existButtHome={true} title="Sourcing Goods Across The World" text1='As a company dedicated to make global products accessible, our global experience, in-depth expertise, and resources have allowed us to assume a unique market position. We have served a large number of clients in more than 40 countries. ' text2="We aim to be a global organization that constantly remains a step ahead in dealing with change, creating new values and opportunities by making trade happen responsibly and innovatively." imgSrc='/static/home-icon.png' imgWidth='150' imgHeight="300">
        
        </Banner>
      <div className={styles.homeButton}>
        <Link href="/products">
      
          <a>
            <p>Products</p>
             <div className={styles.butArrow}><DarkAngle /></div>
            <Image layout='fill' objectFit='cover' src="/static/soap-industry.png" alt='PSI | Products'/>
          </a>
            </Link>
            <Link href="/services">
          <a>
            <p>Services</p>
            <div className={styles.butArrow}><DarkAngle /></div>
            <Image layout='fill' objectFit='cover' src="/static/services-banner.jpg" alt='PSI | Products'/>
          </a>
          </Link>
      </div>
      </div>
      
      <BannerImg imgUrl='/static/home-banner.jpg' sectionLink="certificate-section"/>
 
     <div id="certificate-section">    <Certificate id="certificate-section"/></div>
     <Mission/>
     <HomeServices/>
     
    </div>
  )
}

export default Home;
